Feature/provide shared groups on stored query infos
bakdata/conquery pull request #1376
Opened 2020-10-02 15:16 UTC by thoniTUB

returns the groups a query is shared with on the stored query endpoint

2020-10-07 07:58 UTC, awildturtok requested changes

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/RequestAwareUriBuilder.java
> +		return javax.ws.rs.core.UriBuilder.fromUri(RequestHelper.getRequestURL(request)).path(API);
import

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/RequestAwareUriBuilder.java
> +public abstract class RequestAwareUriBuilder extends javax.ws.rs.core.UriBuilder {
was macht die Klasse außer einer Helper Methode?

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/StoredQueriesProcessor.java
> +		else if(!(query instanceof ManagedQuery)) {
```suggestion

		if(!(query instanceof ManagedQuery)) {
```

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/StoredQuerySingleInfo.java
> +	private boolean isPristineLabel;
öhm, ist das nicht was für Kai?

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/execution/ManagedExecution.java
> +	protected abstract URL _getDownloadURL(UriBuilder url) throws MalformedURLException, IllegalArgumentException, UriBuilderException;
den Unterstrich würde ich vermeiden, verusch hier lieber einen passenderen Namen zu finden

2020-10-07 07:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/StoredQueriesResource.java
> +	public List<ExecutionStatus> getAllQueries(DatasetId datasetId) {
wo ist der User hin?

2020-10-07 07:58 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/integration/tests/ConceptPermissionTest.java
> +		ExecutionStatus status = processor.postQuery(dataset, query, UriBuilder.fromUri(URI.create("http://localhost")), user);
das localhost sieht mir hier falsch aus, was machst du damit? Schau mal ob du eher den eigenen Hostname kriegst?

2020-10-07 10:17 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/RequestAwareUriBuilder.java
> +public abstract class RequestAwareUriBuilder extends javax.ws.rs.core.UriBuilder {
Sie bietet das typische statische Interface vom UriBuilder aber ich könnte sie zu einem Interface machen

2020-10-07 10:20 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/StoredQuerySingleInfo.java
> +	private boolean isPristineLabel;
Meinst du die JsonProperty?

2020-10-07 10:21 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/StoredQueriesResource.java
> +	public List<ExecutionStatus> getAllQueries(DatasetId datasetId) {
Der ist schon du die PostCreate von HAuthorized verfügbar.

2020-10-07 10:24 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/tests/ConceptPermissionTest.java
> +		ExecutionStatus status = processor.postQuery(dataset, query, UriBuilder.fromUri(URI.create("http://localhost")), user);
Der UriBuilder braucht an dieser stelle einfach nur eine Valide URI, benutzt wird diese nicht

2020-10-07 11:24 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/tests/ConceptPermissionTest.java
> +		ExecutionStatus status = processor.postQuery(dataset, query, UriBuilder.fromUri(URI.create("http://localhost")), user);
Aber ich denke auch so, dass `localhost` am portabelsten ist

2020-10-08 12:33 UTC, awildturtok approved these changes

2020-10-08 14:21 UTC, merged