Feature/index for buckets
bakdata/conquery pull request #1394
Opened 2020-10-15 16:14 UTC by awildturtok

2020-10-19 11:53 UTC, thoniTUB submitted a review, later dismissed

2020-10-19 11:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +		Map<TableId, Int2ObjectMap<List<Bucket>>> bucketTables = new HashMap<>();
Map Map List. HolyMoly.

Ich würde es eher `tableToBuckets` nennen, damit es klarer ist, was hier gemappt wird

2020-10-19 11:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +		Map<TableId, Int2ObjectMap<List<Bucket>>> bucketTables = new HashMap<>();
`connectorCBlocks` auch im Namen angleichen

2020-10-19 11:55 UTC, thoniTUB commented
Ups zu früh approved

2020-10-20 06:53 UTC, thoniTUB requested changes

2020-10-20 06:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +					  .get(bucket.getBucket())
Musst du hier nicht auch `getOrDefault` nehmen?

2020-10-20 06:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +						  .get(cBlockId.getBucket().getBucket())
genauso wie hier `getOrDefault`?

2020-10-20 06:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/worker/Worker.java
> +		storage.removeImport(importId);
Ouh, hatte ich das vergessen? Das sollte dann nochin den KW41 rein.
Ich wurde das Löschen aus dem Storage in dem Bucketmanager machen. Und da erst die Buckets und Concepts auf räumen und dann erst aus dem Storage löschen.

2020-10-21 07:11 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +					  .get(bucket.getBucket())
@awildturtok No comment? 🤔

2020-10-21 07:37 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
> +					  .get(bucket.getBucket())
hab ich das nicht behoben? strange sorry

2020-10-21 07:51 UTC, thoniTUB submitted a review, later dismissed

2020-10-21 08:35 UTC, thoniTUB requested changes

2020-10-21 08:35 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/BucketManager.java
>  		for (CBlock cBlock : storage.getAllCBlocks()) {
Hier ist irgendwie ein merge kaputt gegangen und das sollte eigentlich nicht kompilieren, oder wo nimmt er ``requiredBuckets` her?

2020-10-28 09:46 UTC, thoniTUB approved these changes

2020-11-10 11:08 UTC, merged