only deliver queries that are NEW or DONE on Endpoint storedQueries
bakdata/conquery pull request #1397
Opened 2020-10-16 09:55 UTC by thoniTUB

2020-10-19 07:48 UTC, awildturtok requested changes

2020-10-19 07:48 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/StoredQueriesProcessor.java
> +			.peek(q -> System.out.println("After type check:" + q))
log

2020-10-19 07:48 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/execution/ManagedExecution.java
> +		if(url == null || !isReadyToDownload(url, user)) {
Doku, warum die URL Null sein könnte?

2020-10-19 07:48 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/api/StoredQueriesProcessorTest.java
> +		doAnswer((invocation) -> {
Das sollte in einen BeforeAll Block

2020-10-19 07:48 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/api/StoredQueriesProcessorTest.java
> +			if(allowedQueryIds.contains(ManagedExecutionId.Parser.INSTANCE.parse(perm.getInstances().iterator().next()))) {
return allowedQueries...

2020-10-19 13:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/StoredQueriesProcessor.java
> +			.peek(q -> System.out.println("After type check:" + q))
Das war nur fürs debugging, ich entferne es, es gibt ja jetzt einen Test.

2020-10-19 13:41 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/api/StoredQueriesProcessorTest.java
> +			if(allowedQueryIds.contains(ManagedExecutionId.Parser.INSTANCE.parse(perm.getInstances().iterator().next()))) {
@awildturtok was meinst du hier? Ich kann nicht ganz folgen.

2020-10-19 14:10 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/api/StoredQueriesProcessorTest.java
> +			if(allowedQueryIds.contains(ManagedExecutionId.Parser.INSTANCE.parse(perm.getInstances().iterator().next()))) {
anstatt

```
if(f(x))
  return true;
else
  return false;

```

`return f(x)`

2020-10-19 14:46 UTC, awildturtok approved these changes

2020-10-20 06:55 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/api/StoredQueriesProcessorTest.java
> +			if(allowedQueryIds.contains(ManagedExecutionId.Parser.INSTANCE.parse(perm.getInstances().iterator().next()))) {
Oh ja, ich war blind

2020-10-21 09:30 UTC, awildturtok approved these changes

2020-10-21 10:26 UTC, merged