Feature/better default query name
bakdata/conquery pull request #1414
Opened 2020-10-30 16:14 UTC by thoniTUB

Instead of setting the UUID of the execution by default, a default expressive non unique name is now generated upon query initialization.

2020-11-03 08:01 UTC, thoniTUB commented
@awildturtok ich hatte noch mit merkwürdigen bugs zu kämpfen, weshalb der PR etwas größer geworde ist

2020-11-10 11:00 UTC, awildturtok requested changes

2020-11-10 11:00 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/util/NonPersistentNamespaceStorage.java
> +public class NonPersistentNamespaceStorage implements NamespaceStorage {
den hast du ausversehen gepusht?

2020-11-10 13:41 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +		if(offsets.length != 1 && offsets.length != getBucketSize()) {
@awildturtok das war sehr komisch, und hat aufeinmal die CI gefailed, obwohl ich mit dem PR eigentlich nichts in die Richtung angepasst hatte. Das sollten wir im Auge behalten

2020-11-10 13:43 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/ManagedQuery.java
> +		String usedConcepts = sortedContents.computeIfAbsent(CQConcept.class, (clazz)-> List.of()).stream()
hatte ich auch gedacht, aber da ich das label der Query auch als validen Dateinamen nehmen möchte wollte ich nicht, dass der default Name einen komischen Dateinamen erzeugt.

2020-11-10 13:44 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/types/specific/StringTypeDictionary.java
> -	private DictionaryId dictionaryId = new DictionaryId(new DatasetId("null"), UUID.randomUUID().toString());
Das gehört auch noch zum Fix von dem wierden Bug

2020-11-10 13:51 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/util/NonPersistentNamespaceStorage.java
> +public class NonPersistentNamespaceStorage implements NamespaceStorage {
Mhhm, ich glaube den habe ich im Test mal gebraucht, ihn aber letztlich vereinfacht sodass der Store nicht mehr benötigt wurde

2020-11-10 14:28 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/util/NonPersistentNamespaceStorage.java
> +public class NonPersistentNamespaceStorage implements NamespaceStorage {
Habe Sie wieder raus geschmissen

2020-11-10 14:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/execution/ResultProcessor.java
> +					SerializingStore.SAVE_FILENAME_REPLACEMENT_MATCHER.matcher(exec.getLabel()).replaceAll("_"),
Ist raus

2020-11-18 16:35 UTC, awildturtok approved these changes

2020-11-19 08:36 UTC, merged