use default validity date column if none provided
bakdata/conquery pull request #1435
Opened 2020-11-18 16:31 UTC by awildturtok

2020-11-20 15:36 UTC, thoniTUB requested changes

2020-11-20 15:36 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/TableExportQuery.java
> +					validityDateColumn = connector.getValidityDates().get(0).getColumn();
Achtung ValidityDates kann leer sein!
Es gibt Konzepte ohne ValidityDate

2020-12-01 09:50 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +					if (exportDescription.getValidityDateColumn() == null && !bucket.eventIsContainedIn(event, exportDescription.getValidityDateColumn(), dateRange)) {
```suggestion
					if (exportDescription.getValidityDateColumn() != null && !bucket.eventIsContainedIn(event, exportDescription.getValidityDateColumn(), dateRange)) {
```

2020-12-04 11:05 UTC, thoniTUB approved these changes

2020-12-04 11:05 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +	public abstract int getString(int event, @NotNull Column column);
Zieht das @NotNull bei abstrakten Methoden? Ich glaube nicht das Lombok klassenübergreifend Code erzeugen kann

2020-12-04 11:07 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +	public abstract int getString(int event, @NotNull Column column);
Leider nein :(

2020-12-07 13:01 UTC, merged