Allow exclusion from SecondaryIdQuery
bakdata/conquery pull request #1440
Opened 2020-11-23 16:31 UTC by awildturtok

2020-11-24 15:08 UTC, thoniTUB requested changes

2020-11-24 15:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +							excludeFromSecondaryIdQuery
Ich denke hier solltest du die SecondaryId aus der QueryDescription der CopnceptNode übergeben, wenn für das Concept eine SecondaryId beachtet werden sollte und eine leere Liste bzw. `null` wenn nicht.

2020-11-24 15:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		usedSecondaryIds = Arrays.stream(table.getResolvedConnector().getTable().getColumns())
In `usedSecondaryIds` nicht die vom Datenset definierten SecondaryIds speichern sondern checken, ob die von der QueryDescription übergebene vorhanden ist und ansonsten einen Fehler werfen

2020-11-24 15:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/DateRestrictingNode.java
> +		restricted.retainAll(ctx.getDateRestriction());
:D was war das denn?

2020-11-24 15:24 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +
äh, bei den Dictionaries ist es auf's erst ja nur das PrimaryDictionary, das wird auf den Workern nur einmal für's debugging benutzt. Die richtigen Dictionaries würde ich erstmal Arrow abwarten

2020-11-24 15:24 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/SecondaryIdQuery.java
> +		Map<TableId, ColumnId> withSecondaryId = new HashMap<>();
Eine Table kann mehrere Spalten mit SecondaryId haben

2020-11-24 15:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +	private boolean excludeFromSecondaryIdQuery = false;
ja, default sollte in einer SecondaryId-Query sein, dass das Konzept betrachtet wird. Die Nutzer sollen aber selektiv Konzepte aus der SecondaryId-Ebene entfernen

2020-11-24 15:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/SecondaryIdQuery.java
> +		Map<TableId, ColumnId> withSecondaryId = new HashMap<>();
ah! nice

2020-11-24 15:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +				childPerKey.computeIfAbsent(key, k -> this.createChild(secondaryIdColumn, myCtx, bucket))
was meinst du? das ist ein kack name, aber der richtige Context

2020-11-24 15:32 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		if (tableActive && excludeFromSecondaryIdQuery && usedSecondaryIds.contains(ctx.getActiveSecondaryId())) {
die usedSecondaryIds setzen wir ein paar Zeilen weiter oben, das FrontEnd schickt uns diese Info nicht. Nur welche SecondaryId betrachtet werden soll, und welche Konzept-Knoten aus dieser Betrachtung explizit entfernt werden sollen

2020-11-24 15:33 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/DateRestrictingNode.java
> +		restricted.retainAll(ctx.getDateRestriction());
tipper von mir :/

2020-11-24 15:34 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/DateRestrictingNode.java
> +		restricted.retainAll(ctx.getDateRestriction());
aber guter Punkt, das muss ich noch hotfixen

2020-11-24 16:13 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +				childPerKey.computeIfAbsent(key, k -> this.createChild(secondaryIdColumn, myCtx, bucket))
Ich wollte eigentlich ein gollum my precious gif hinzufügen

2020-11-24 16:20 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		if (tableActive && excludeFromSecondaryIdQuery && usedSecondaryIds.contains(ctx.getActiveSecondaryId())) {
Du kannst die SecondaryId doch aus dem Request des Frontends in den `QueryPlanContext` stecken und im CQConcept wird dann mithilfe von `excludeFromSecondaryIdQuery`, den SecondaryIds aus dem `resolvedConnector` und der gefragten SecondaryId aus dem  `QueryPlanContext` in `createQueryPlan` das `usedSecondaryId` für die `ConceptNode` gebaut

2020-11-25 11:04 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/DateRestrictingNode.java
> +		restricted.retainAll(ctx.getDateRestriction());
habe es nachgereicht

2020-11-25 11:05 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +
Und hier ist es ja sauber gekapselt und nicht leaky am rumschwirren

2020-11-25 11:06 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/SecondaryIdQuery.java
> +		Map<TableId, ColumnId> withSecondaryId = new HashMap<>();
Cool, man braucht die Table nicht mal

2020-11-25 11:08 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +			result.add(ArrayUtils.insert(0, child.getValue().result().getValues(), child.getKey()));
Insert vergrößert das Array

2020-11-25 11:09 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +				childPerKey.computeIfAbsent(key, k -> this.createChild(secondaryIdColumn, myCtx, bucket))
:D

2020-11-25 11:10 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		if (tableActive && excludeFromSecondaryIdQuery && usedSecondaryIds.contains(ctx.getActiveSecondaryId())) {
Das Feld wird trotzdem benötigt, wenn ein Benutzer explizit ein Konzept ausschließen will

2020-11-26 11:42 UTC, thoniTUB requested changes

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/Table.java
> +	public boolean distinctSecondaryIds() {
```
/**
 * Validates a bean predicate method as returning true. Bean predicates must be of the form
 * {@code isSomething} or they'll be silently ignored.
 */
```
also **isDistinctSecondaryIds()** sonst wird nicht validiert

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +							excludeFromSecondaryIdQuery,
Parameter kann weg. Setze für die ConceptNode einfach keine SecondaryId wenn `excludeFromSecondaryIdQuery == true`.
Ich würde es auch `useSecondaryId (dafault false)` nennen, denn die Negation verwirrt.

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +														  .orElse(null);
```suggestion
			final SecondaryId selectedSecondaryId = useSecondaryId ? Arrays.stream(connector.getTable().getColumns())
														  .map(Column::getSecondaryId)
														  .filter(Objects::nonNull)
														  .filter(o -> Objects.equals(context.getSelectedSecondaryId(), o))
														  .collect(MoreCollectors.toOptional())
														  .orElse(null) : null;
```

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		if (excludeFromSecondaryIdQuery
Ich sehe hier kein Mehrwert von `excludeFromSecondaryIdQuery`.
Sollte ein ConceptNode ohne SecondaryId ausgeführt werden  dann sollte `selectedSecondaryId == null` und `ctx.getActiveSecondaryId()== null` sein. Für normale ConceptQueries als auch für SecondaryIdQueries

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +		QueryExecutionContext ctxWithPhase = ctx.withSecondaryIdQueryPlanPhase(QueryExecutionContext.SecondaryIdQueryPlanPhase.WithId)
Können die Phasen jetzt nicht auch weg?

2020-11-26 11:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +		QueryExecutionContext ctxWithPhase = ctx.withSecondaryIdQueryPlanPhase(QueryExecutionContext.SecondaryIdQueryPlanPhase.WithId)
Eine ConceptNode wird doch nur ausgeführt, wenn ihre secondaryId mit der gerade aktiven über einstimmt (bzw. beide `null` sind)

2020-12-03 08:20 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +							excludeFromSecondaryIdQuery
gute Idee

2020-12-07 13:38 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/specific/ConceptNode.java
> +		if (excludeFromSecondaryIdQuery
Hat mich etwas gekostet um zu bemerken, dass es einfach nur selectedSecondaryId == ctx.getActiveSecondaryId ist haha

2020-12-07 15:27 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +	private boolean excludeFromSecondaryIdQuery = false;
Ich bin noch der Meinung, Dass das standardmaßig `true` sein sollte

2020-12-07 15:44 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +				;
🤔 looks empty

2020-12-07 15:44 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/types/parser/specific/string/StringParser.java
>  public class StringParser extends Parser<Integer> {
Gehören die Änderungen am StringParser hierein?

2020-12-07 15:47 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/SecondaryIdQueryPlan.java
> +				;
```suggestion
```

2020-12-09 09:30 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/types/parser/specific/string/StringParser.java
>  public class StringParser extends Parser<Integer> {
Ah, das ist der BugFix für PrefixSuffix

2021-01-14 11:11 UTC, closed without merging