Label and Description for SecondaryId
bakdata/conquery pull request #1485
Opened 2020-12-09 11:56 UTC by awildturtok

2021-01-12 07:45 UTC, thoniTUB requested changes

2021-01-12 07:45 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/admin/rest/AdminProcessor.java
> +		log.info("Received new SecondaryId[{}]", secondaryId.getId());
Eins reicht denke ich

2021-01-12 08:22 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/SecondaryIdQuery.java
> +					  .map(ContainedEntityResult::listResultLines)
ja

2021-01-12 08:24 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/IQuery.java
> +	public long countResults(List<EntityResult> results) {
jein, das ist eine klassen methode, damit es beim addResult gezählt werden kann spezifisch der ausgeführten Query, ohne sich die Klasse anschauen zu müssen oä

2021-01-12 08:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/admin/ui/TablesUIResource.java
> +			throw new NotFoundException("Could not find Table " + tableId.toString());
Das war nur der falsche import:  `import javax.ws.rs.NotFoundException;`

2021-01-12 14:07 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/messages/namespaces/specific/RemoveSecondaryId.java
> +		synchronized (context.getStorage()) {
habe jetzt die Methode im zugrunde liegenden Storage synchronized gemacht, macht Sinn!

2021-01-12 14:08 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/jackson/serializer/NsIdReferenceDeserializer.java
> +				Optional<T> result = idResolveContext.getOptional(id);
Der Change war nur zum debugging da, würde ihn aber lassen, weil es manchmal gut ist zu sehen, welchen Kontext man genau bekommt.

2021-01-13 05:59 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/admin/ui/TablesUIResource.java
> +			throw new NotFoundException("Could not find Table " + tableId.toString());
Oki

2021-01-13 06:01 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/IQuery.java
> +	public long countResults(List<EntityResult> results) {
Ah okay, dann bitte Doku ran machen.

2021-01-13 15:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/admin/rest/AdminProcessor.java
> +		final List<Column> dependents = namespace.getStorage().getTables().stream()
habe mal alles was Sinn macht synchronized markiert, multithreading wäre hier eh schlecht

2021-01-13 15:44 UTC, thoniTUB approved these changes

2021-01-13 15:44 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/IQuery.java
> +	 * Implement Query-type aware counting of results. Standard method is counting person-lines.
```suggestion
	 * Implement Query-type aware counting of results. Standard method is counting unique entities.
```

2021-01-14 11:27 UTC, merged