Masked add implementation for CDateSet
bakdata/conquery pull request #1526
Opened 2021-01-07 08:28 UTC by awildturtok

2021-01-12 17:48 UTC, thoniTUB requested changes

2021-01-12 17:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
>  	}
Mir ist gerade aufgefallen, das der Member `asDescendingSetOfRanges` nur ein einziges Mal  berechnet wird und danach nicht nicht mehr neuberechnet wird, wenn sich das Set verändert 🌵

2021-01-12 17:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
>  	}
genauso `asRanges`

2021-01-12 17:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
> +			searchEnd = mask.rangesByLowerBound.floorKey(toAdd.getMaxValue());
Sollte es hier nicht `.ceilingKey()` sein? Sonst kann es doch sein, dass das obere Ende der Maske nicht beachtet wird

2021-01-12 17:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
> +			searchEnd = mask.rangesByLowerBound.floorKey(toAdd.getMaxValue());
Ah, CDateSet lässt keine sich überlappenden Ranges zu, oder?

2021-01-13 08:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
>  	}
asDescendingSetofRanges wird auch nirgends benutzt

asRanges ist ok, weil es eine referenz auf rangesbylowerbound hält

2021-01-13 08:30 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
> +			searchEnd = mask.rangesByLowerBound.floorKey(toAdd.getMaxValue());
genau, überlappungen werden beim hinzufügen gelöst deswegen sind da auch ne menge deletions drin.

2021-01-13 08:41 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
>  	}
bei `asRanges` wird `.values()` aufgerufen. Ist das gebacked von der Map?

2021-01-13 11:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/common/CDateSet.java
>  	}
jap

2021-01-13 15:29 UTC, merged