Feature/validate column types
bakdata/conquery pull request #1706
Opened 2021-03-16 17:47 UTC by awildturtok

2021-03-17 08:17 UTC, thoniTUB requested changes

2021-03-17 08:17 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/concepts/Connector.java
>  		return passed;
Die Validierung kann auch in nach ValidityDate

2021-03-17 08:17 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/concepts/filters/SingleColumnFilter.java
> +	}
Kann man diese Validierung fehlschlagen lassen?

2021-03-17 08:17 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/concepts/filters/SingleColumnFilter.java
> +	}
Ah okay, `getAcceptedColumnTypes` wird überschrieben

2021-03-17 08:17 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/concepts/filters/SingleColumnFilter.java
> +	}
Das Set könntets du noch static machen

2021-03-17 08:19 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/concepts/filters/SingleColumnFilter.java
> +	}
> Ah okay, getAcceptedColumnTypes wird überschrieben

Dann mach ich hier Doku für

2021-03-17 08:24 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/concepts/Connector.java
> +		return valid;
macht sinn!

2021-03-29 13:48 UTC, thoniTUB approved these changes

2021-03-31 10:01 UTC, thoniTUB approved these changes

2021-03-31 10:08 UTC, merged