Use direct array implementation for CBlock backing values now leveraging properly encapsulated API
bakdata/conquery pull request #1735
Opened 2021-03-25 09:02 UTC by awildturtok

Traces show ~15% time spent in findKey of Int2IntArrayMap for CalculateCblocksJob

2021-03-29 12:42 UTC, thoniTUB requested changes

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
>  	}
Hier würde ich eine FactoryMethod für einen CBlock draus machen und den NoArgsConstructor private machen damit er nur von Jackson benutzt wird

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +				minDate[index] = minValue;
```suggestion
			if (minDate[index] == Integer.MIN_VALUE) {
				minDate[index] = minValue;
```

oder sehe ich das falsch?

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +		}
```suggestion
		Arrays.fill(includedConcepts, 0);
		Arrays.fill(minDate, Integer.MIN_VALUE);
		Arrays.fill(maxDate, Integer.MAX_VALUE);
```
ändert denke ich nichts an der Performance

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +		}
Hattest du nicht sonst mit den gegenüberliegenden extrema gearbeitet, also bei min MAX_VALUE gesetzt um einen Special-Case zu symbolisieren und andersherum

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +			if (maxDate[index] != Integer.MAX_VALUE) {
Hier auch

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +				minDate[index] = minValue;
sonst ist der else branch immer MIN_VALUE

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +				maxDate[index]  = min;
```suggestion
				int max = Math.max(maxDate[index], maxValue);
				maxDate[index]  = max;
```

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +	}
Okay, es ist private, aber es wird von public Funktionen ohne check aufgerufen

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/jobs/CalculateCBlocksJob.java
> +				cBlock.initIndizes(bucketManager.getEntityBucketSize());
ah es gibt schon eine FactoryMethod. Darin kann doch das initIndizes gemacht werden

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/jobs/ImportJob.java
> +				bucketSize,
Die BucketSize kann eigentlich aus dem Bucket raus, wenn die initIndizes geinlined wird

2021-03-29 12:42 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/util/support/TestConquery.java
> +		log.info("Tearing down dataset", new Exception("MARKER"));
Kann weg oder?

2021-03-29 13:10 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +		}
Ja aber das hat daten ohne validity date verhindert bzw einen special case draus gemacht.

2021-03-29 13:59 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +	}
Gotta go faast

2021-03-29 14:01 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/CBlock.java
> +	}
Hab nen min Check gemacht, max bräuchte ich wieder die size

2021-03-31 08:39 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/jobs/CalculateCBlocksJob.java
> +				cBlock.initIndizes(bucketManager.getEntityBucketSize());
good catch!

2021-03-31 10:00 UTC, thoniTUB approved these changes

2021-03-31 10:00 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/Bucket.java
> +	//TODO migrate these back to arrays again, like CBlock#getEntityIndex (and unify those)
Für einen anderen PR?

2021-03-31 10:00 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/util/support/TestConquery.java
> +		log.info("Tearing down dataset", new Exception("MARKER"));
Ist noch drinne

2021-04-07 14:20 UTC, merged