adds checkbox to disable auto-refresh
bakdata/conquery pull request #1777
Opened 2021-04-13 14:58 UTC by awildturtok

2021-04-21 07:41 UTC, thoniTUB requested changes

2021-04-21 07:41 UTC, thoniTUB commented on backend/src/main/resources/com/bakdata/conquery/resources/admin/ui/jobs.html
> +            <input type="checkbox" id="update" name="update" checked="checked">
Laut https://developer.mozilla.org/de/docs/Web/HTML/Element/Input/checkbox#checked ist `checked` ein boolean

2021-04-21 10:45 UTC, awildturtok commented on backend/src/main/resources/com/bakdata/conquery/resources/admin/ui/jobs.html
> +            <input type="checkbox" id="update" name="update" checked="checked">
Nice, ich hatte nur ein paar merkwürdige SO threads dazu aber nicht an mdn gedacht

2021-04-23 08:50 UTC, thoniTUB approved these changes

2021-04-23 08:53 UTC, merged