Feature/pathparam provider idref
bakdata/conquery pull request #1832
Opened 2021-04-30 16:30 UTC by awildturtok

2021-05-03 14:14 UTC, thoniTUB commented
In der CI sieht es gerade so aus, als würde etwas nicht synchroniziert sein.

2021-05-05 09:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefParamConverter.java
> +		}
ne weil ich an der stelle wo der Provider instantiiert wird das Dataset noch nicht kenne

2021-05-05 12:37 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/ApiV1.java
> +		environment.register(new IdRefPathParamConverterProvider(manager.getDatasetRegistry()));
ich hab es in beiden registriert, wie würde ich es so registrieren, dass es eins für beide gibt?

2021-05-05 12:57 UTC, thoniTUB requested changes

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/worker/DatasetRegistry.java
>  			workers.keySet().removeIf(w->w.getDataset().equals(id));
Wie geht das löschen jetzt?

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefParamConverter.java
> +		}
Ich meine der IdRefPathParamConverterProvider bekommt ja den Typen zu sehen und kann daraufhin entweder einen IdRefParamConverter mit einer DatasetRegistry oder mit der MetaCentralRegistry erzeugen. 
Die Entscheidung mit welcher Registry der Id resolved werden soll, sollte nicht an jeder Id getestet werden, sondern einmalig pro IdTyp,

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefPathParamConverterProvider.java
> +		return new IdRefParamConverter(parser, datasetRegistry);
```suggestion
		if (NamespacedIdentifiable.class.isAssignableFrom(rawType)) {
			return new IdRefParamConverter(parser, datasetRegistry);
		}
		return new IdRefParamConverter(parser, datasetRegistry.getMetaRegistry());
```

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefPathParamConverterProvider.java
> +		return new IdRefParamConverter(parser, datasetRegistry);
Hier würde ich die Unterscheidung machen nicht im IdRefParamConverter. Hier wird es nur einmal pro Typ auf gerufen und nicht für jeden zu desezializierenden Wert.

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/admin/AdminServlet.java
> +		jerseyConfig.register(new IdRefPathParamConverterProvider(manager.getDatasetRegistry()));
Ich würde die MetaRegistry, explizit übergeben, damit hier klar ist, dass beide Arten von Ids versucht werden aufzulösen

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/ManagedForm.java
> +import com.univocity.parsers.csv.CsvWriter;
Ich glaube die Dependency ist mir ausversehen hierein gerutsch

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/ManagedQuery.java
> +import com.univocity.parsers.csv.CsvWriter;
Hier auch

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefPathParamConverterProvider.java
> +		}
Wäre es nicht besser diesen Provider zu benutzen, wenn die annotierten Felder auch mit @NsIdRef, bzw @MetaIdRef annotiert sind?
Bin mir nicht sicher

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/admin/rest/AdminProcessor.java
> +	public void addUserToGroup(Group group, User user) {
Nice, die Klasse ist ganz schön geschrumpft

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/admin/rest/AuthOverviewResource.java
> +			.header("Content-Disposition",  String.format("attachment; filename=\"authOverview_%s.csv\"", group.getName()))
Kannst du hier bitte
```
.header("Content-Disposition", String.format("attachment; filename=\"authOverview_%s.csv\"", group.getName()
```
mit der Methode aus ResultUtils ergänzen

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +		return out;
Das ist noch ein alter Stand

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/ApiV1.java
> +		environment.register(new IdRefPathParamConverterProvider(manager.getDatasetRegistry()));
Dann habe ich den anderem Aufruf ncoh nciht gesehen. Wir hätten sonst noch eine RESTUtil Klasse, die auf alle RequestContainer aufgerufen wird

2021-05-05 12:57 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/concept/specific/CQConcept.java
> +	public void collectNamespacedObjects(Set<NamespacedIdentifiable<?>> namespacedIds) {
Der Parametername bezieht sich noch auf Ids

2021-05-05 15:07 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/jackson/IdRefPathParamConverterProvider.java
> +		return new IdRefParamConverter(parser, datasetRegistry);
Musste sie dafür splitten aber ist besser so

2021-05-05 15:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/admin/rest/AuthOverviewResource.java
> +			.header("Content-Disposition",  String.format("attachment; filename=\"authOverview_%s.csv\"", group.getName()))
FileUtil

2021-05-06 10:01 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +		return out;
was meinst du?

2021-05-06 11:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +		return out;
Die Methode gibt auf develop an der stelle nciht mehr

2021-05-06 13:14 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +		return out;
ist weg

2021-05-06 13:19 UTC, thoniTUB submitted a review, later dismissed

2021-05-06 13:19 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/forms/export_form/ExportForm.java
>  	}
Rein oder weg. Was meinst du?

2021-05-06 13:27 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/forms/export_form/ExportForm.java
>  	}
ah, weg natürlich

2021-05-06 13:40 UTC, merged