Feature/improve excel output
bakdata/conquery pull request #1859
Opened 2021-05-11 11:00 UTC by thoniTUB

Organizes the data in tables, uses freeze pane for header and id columns, corrects number formattings and auto-widths columns:
![image](https://user-images.githubusercontent.com/12283268/117805003-c06a7300-b258-11eb-821b-116bd2c40db5.png)

2021-05-12 12:55 UTC, awildturtok requested changes

2021-05-12 12:55 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/excel/ExcelRenderer.java
> +        for (int colIdx = 0; colIdx < table.getColumnCount(); colIdx++) {
kannst du hier noch eien check drauf machen, dass es nicht DATE_SET ist?

2021-05-12 12:55 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/excel/ExcelRenderer.java
> +        return resultLines.map(l -> this.writeRowsForEntity(infos,l, () -> sheet.createRow(currentRow.getAndIncrement()), cfg)).reduce(0, Integer::sum);
mapToInt.sum

2021-05-17 12:05 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/excel/ExcelRenderer.java
> +        return resultLines.map(l -> this.writeRowsForEntity(infos,l, () -> sheet.createRow(currentRow.getAndIncrement()), cfg)).reduce(0, Integer::sum);
👍

2021-05-17 12:05 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/excel/ExcelRenderer.java
> +        for (int colIdx = 0; colIdx < table.getColumnCount(); colIdx++) {
👍

2021-05-17 14:22 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/excel/ExcelRenderer.java
> +        return resultLines.map(l -> this.writeRowsForEntity(infos,l, () -> sheet.createRow(currentRow.getAndIncrement()), cfg)).mapToInt(Integer::intValue).sum();
das mapToInt kannst du direkt nach resultLines machen

2021-05-17 14:23 UTC, awildturtok approved these changes

2021-05-18 14:37 UTC, merged