Improve Import Performance
bakdata/conquery pull request #1954
Opened 2021-06-25 10:52 UTC by thoniTUB

2021-06-25 12:46 UTC, awildturtok approved these changes

2021-06-25 12:46 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/specific/string/StringTypeEncoded.java
> +				.maximumSize(100)
mach einfach softValues das darf ruhig so viel benutzen wie es will

2021-06-25 12:46 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +		if (parentIndex != -1) {
kriegst du es hin den stack explizit zu implementieren statt rekursion? dann ballerst du der jvm keine riesen stacks um die ohren. weil den call wird es nicht eliminieren können (wobei möglich, dass es die rekursion versteht und für dich unrolled, aber nicht sehr plausibel)

2021-07-07 09:21 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/specific/string/StringTypeEncoded.java
> +				.maximumSize(100)
benutzt jetzt soft values

2021-07-07 09:22 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +		if (parentIndex != -1) {
Ist jetzt iterativ durch umgedrehtes einfügen der Wörter.

2021-07-07 12:16 UTC, awildturtok requested changes

2021-07-07 12:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/specific/string/StringTypeEncoded.java
> +	private final LoadingCache<Integer,String> elementCache;
Dokumentation warum das da ist

2021-07-07 12:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
>  	@Getter
Getter einfach auf Klasse machen?

2021-07-07 12:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
>  @CPSType(id="SUCCINCT_TRIE", base=Dictionary.class)
Da du ja jetzt verstehst was die Klasse macht, bitte einmal Doku schreiben, oder ggf einen guten Wikipedia Artikel dazu suchen und verlinken

2021-07-07 12:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +			for (int i = value.length-1; i >= 0; i--) {
Doku dafür, dass wir Rückwärts laufen etc

2021-07-07 12:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +	private void getReverseInternal(ByteArrayList buf, int nodeIndex) {
brauchts die Method jetzt noch?

2021-07-08 10:39 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
>  	@Getter
Es sind ein paar member dabei die von aus nicht zugänglich sein sollen

2021-07-08 10:42 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +	private void getReverseInternal(ByteArrayList buf, int nodeIndex) {
ist gelöscht

2021-07-08 11:06 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
>  @CPSType(id="SUCCINCT_TRIE", base=Dictionary.class)
Doku ist dranne

2021-07-08 11:06 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/specific/string/StringTypeEncoded.java
> +	private final LoadingCache<Integer,String> elementCache;
Doku ist dranne

2021-07-08 11:06 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/dict/SuccinctTrie.java
> +			for (int i = value.length-1; i >= 0; i--) {
Doku ist dranne

2021-07-08 11:25 UTC, awildturtok approved these changes

2021-07-13 11:27 UTC, merged