Feature/arrow i18n for values
bakdata/conquery pull request #2001
Opened 2021-08-02 11:17 UTC by thoniTUB

2021-08-02 11:26 UTC, awildturtok requested changes

2021-08-02 11:26 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private final static Map<Class<? extends ResultType>, FieldCreatorFactory> FIELD_MAP = Map.of(
FieldCreatorFactory ist der name evtl falsch?

2021-08-02 11:26 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private static Field integerField(ResultInfo info, PrintSettings settings) {
könntest du den namen nicht schon hoch ziehen, und dann hättest du keine info oder pritnsettings als parameter?

2021-08-02 12:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private final static Map<Class<? extends ResultType>, FieldCreatorFactory> FIELD_MAP = Map.of(
jep, ist gedoppelt :D Sowas wollte ich nicht: http://laser.cs.umass.edu/documentation/javadoc/lj_1.5/laser/lj/ast/FactoryFactory.html

2021-08-02 13:02 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private static Field integerField(ResultInfo info, PrintSettings settings) {
Ich habs hochgebubbelt, leider brauch ich weiterhin zwei Parameter, weil der List-Vector die info braucht

2021-08-02 13:12 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private interface FieldCreatorFactory extends BiFunction<ResultInfo, PrintSettings, Field> {
ach ich seh gerade dass du das Interface hier definierst. Warum Droppst du es nicht einfach? Das ist ja einfach nur ein stumpfes alias was etwas informatin versteckt

2021-08-02 14:51 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ArrowUtil.java
> +	private interface FieldCreatorFactory extends BiFunction<ResultInfo, PrintSettings, Field> {
jep, stimmt. ich inline es mal

2021-08-03 09:06 UTC, awildturtok approved these changes

2021-08-03 09:29 UTC, merged