Don't try to handle unencodable values
bakdata/conquery pull request #2017
Opened 2021-08-12 09:47 UTC by awildturtok

2021-08-12 11:42 UTC, thoniTUB commented
Hier war noch ein zweiter Fehler, weshalb die Query wohl nicht als fehlgeschlagen markiert wurde:
```
ERROR [2021-08-12 11:06:47]     c.b.c.m.j.JobExecutor   Job Manager slow ManagerNode    Job ReactingJob(message=CollectQueryResult(result=ShardResult(queryId=??????????.6bf4467b-51b5-4e2a-8f14-e8ff7b9cf5b2, workerId=?????????.worker_?????????_bd143742-1abf-4d42-b4cb-83496
a135237, startTime=2021-08-12T11:06:38.513080, finishTime=2021-08-12T11:06:47.321961)) for dataset ?????????) failed
java.lang.RuntimeException: Failed while processing the message CollectQueryResult(result=ShardResult(queryId=?????????.6bf4467b-51b5-4e2a-8f14-e8ff7b9cf5b2, workerId=?????????.worker_?????????_bd143742-1abf-4d42-b4cb-83496a135237, startTime=2021-08-12T11:06:38.513080, f
inishTime=2021-08-12T11:06:47.321961)) for dataset ?????????
        at com.bakdata.conquery.models.jobs.ReactingJob.execute(ReactingJob.java:21)
        at com.bakdata.conquery.models.jobs.JobExecutor.run(JobExecutor.java:117)
Caused by: java.lang.NullPointerException: null
        at com.bakdata.conquery.models.messages.namespaces.specific.CollectQueryResult.react(CollectQueryResult.java:27)
        at com.bakdata.conquery.models.messages.namespaces.specific.CollectQueryResult.react(CollectQueryResult.java:18)
        at com.bakdata.conquery.models.messages.network.specific.ForwardToNamespace.react(ForwardToNamespace.java:29)
        at com.bakdata.conquery.models.messages.network.specific.ForwardToNamespace.react(ForwardToNamespace.java:18)
        at com.bakdata.conquery.models.jobs.ReactingJob.execute(ReactingJob.java:19)
        ... 1 common frames omitted
```

Kannst du den bitte noch gleich mit fixen?

2021-08-13 07:32 UTC, thoniTUB requested changes
Den anderen Fehler bitte auch gleich fixen

2021-08-13 07:39 UTC, awildturtok commented
Ich hab mir das mal angeschaut @thoniTUB, warum kann da überhaupt results leer sein? Es gibt eine gesetzte leere Liste, an manchen Stellen wird es gesetzt aber nie auf null. Macht unser Jackson irgendwo empty => null?

2021-08-13 11:49 UTC, thoniTUB commented
@awildturtok kann es sein, dass 
QueryExecutor.java
```
allDone.thenApply((ignored) -> futures.stream()
												  .map(CompletableFuture::join)
												  .flatMap(Optional::stream)
												  .collect(Collectors.toList()))
				   .whenComplete((results, exc) -> result.finish(results, Optional.ofNullable(exc), worker));

```
`results` auf null setzen kann?

2021-08-13 12:14 UTC, awildturtok commented
ahh, klar, du hast recht!

Wenn eine Exception fliegt, wird `whenComplete` mit null und der Exception befüllt! Das hab ich übersehen

2021-08-13 12:29 UTC, thoniTUB requested changes

2021-08-13 12:29 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/messages/namespaces/specific/CollectQueryResult.java
> +@NoArgsConstructor
Der Kann weg, AllArgs sollte für Jackson reichen und `results` sollte nie null sein.

Sollte `result.getResults() == null` sein, dann würde der Code noch in ManagedQuery::addResult failen, da ist auch kein null-Check. Der Log kann da aber auch weg

2021-08-13 14:16 UTC, thoniTUB approved these changes

2021-08-17 09:46 UTC, merged