Command implementing capability to do script based Migrations
bakdata/conquery pull request #2034
Opened 2021-08-18 08:25 UTC by awildturtok

2021-08-18 13:35 UTC, thoniTUB commented
@Njimefo Ich habe dich mal mit zum Review eingeladen, falls du schonmal Lust und Kapazität hast

2021-08-18 14:25 UTC, thoniTUB requested changes
Ich sehe nur das ändern und einfügen von keys gravierend, sonst bene 👍

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +		try (final Cursor cursor = inStore.openCursor(readTx)) {
Musst du hier noch ein transaction timeout beachten oder gibt es keins?

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				final String key = mapper.readValue(cursor.getKey().getBytesUnsafe(), String.class);
es ist vielleicht an der  stelle performanter wenn du dir direkt einen Reader erzeugst mit `mapper.readerFor(String)`

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				final Tuple<?> migrated =
Wenn du hier anstatt Tuple eine Pair Klasse nimmst von commons oder fastutil, dann kannst du später mit `migrated.key()` und `.value()` daraufzugreifen

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				}
willst du hier wirklich die Bytes ausgeben, das kann die Konsole zerschießen

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				outStore.putRight(writeTx, keyIter, valueIter);
Das kann leider zu einem korrupten Store führen, da du den key vermutlich änderst
> Can be used if it is a priori known that the key is definitely greater than any other key in the Store.

2021-08-18 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +		if (!writeTx.commit()) {
Ist das ein flush ?

2021-08-18 14:27 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				.type(Arguments.fileType());
das liegt daran, dass ich out erzeugen kann, aber in erwartungen dran habe. Es gibt sogar ein flag wie canCreate oder sowas aber das funktioniert nicht richtig.

2021-08-18 14:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +		try (final Cursor cursor = inStore.openCursor(readTx)) {
laut Doku, wenn kein Timeout gesetzt ist, hat es auch keins: `jetbrains.exodus.env.EnvironmentConfig#setEnvMonitorTxnsTimeout`

2021-08-18 14:31 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				.required(true);
ich kann sie nicht aus dem inputStore ableiten, weil ich die da auch schon zum öffnen brauche, kann aber schauen, ob ich es dann einen Configured bzw ConqueryCommand machen kann und dann krieg ich es aus der `config.json`

2021-08-18 14:32 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				final Tuple<?> migrated =
Tuple ist ein Groovy native, deswegen hab ich das genommen

2021-08-18 14:33 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				outStore.putRight(writeTx, keyIter, valueIter);
stimmt hab ich schon gefixt und wohl nicht gepusht. Danke

2021-08-18 14:40 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +		if (!writeTx.commit()) {
Ja

2021-08-18 14:41 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				final Tuple<?> migrated =
Ah wenn das so ist

2021-08-18 14:42 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				final String key = mapper.readValue(cursor.getKey().getBytesUnsafe(), String.class);
ah, gute idee hab es für alles umgesetzt und ganz hochgezogen.

2021-08-18 14:55 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				}
naja, ist nur für debug Zwecke aber das sind ja auch die keys also schon les/schreibbare sachen?

2021-08-19 07:35 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				}
Aber im smile format und muss nicht ich nicht so aligned sein wie UTF8, so dass schnell mal ein Steuerzeichen produziert wird durch den String Konstruktor

2021-08-19 07:38 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +		if (!writeTx.commit()) {
Stimmt ist eine riesen Transaktion. Ich habe auf die schnelle nichts gefunden ob Xodus kleine oder große Transaktionen mag

2021-08-19 07:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				.help("Migration Script.")
Kannst du hier noch mehr infos zum Script reinpacken? Einen Link oder so damit man sehen kann was die Parameter und der Rückgabewert sein sollen?

2021-08-19 07:49 UTC, thoniTUB approved these changes

2021-08-19 09:14 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				.help("Migration Script.")
Habe ein example.groovy skript beigefügt.

2021-08-19 09:15 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/commands/MigrateCommand.java
> +				}
dann löschen, weil wir auf trace schon alles loggen?

2021-08-19 14:48 UTC, thoniTUB approved these changes

2021-08-19 14:48 UTC, merged