Reset, don't clone
bakdata/conquery pull request #2061
Opened 2021-08-31 14:49 UTC by awildturtok

2021-09-01 11:58 UTC, thoniTUB requested changes
Ich glaube es sieht gut aus soweit. Nur das init in execute auf gerufen wird stört mich, ich würde es reset nennen

2021-09-01 11:58 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/EventIterating.java
> +	public void init(Entity entity, QueryExecutionContext context);
Doku

2021-09-01 11:58 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	}
ist das nicht eher ein reset?

2021-09-01 12:08 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/AbsoluteFormQueryPlan.java
> +	}
ja ich will defaults vermeiden, das führt nur zu unnötigen fehlern. ich denke sogar, dass ich die init überall ausfüllen werde und ggf doppelungen haben werde

2021-09-01 12:09 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/FormQueryPlan.java
> +		init(ctx, entity);
ne du hast recht, kann mir auch wie du vorstellen, dass man init vorzieht

2021-09-01 12:10 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	}
init ist ein reset ja, kann es umbenennen.

2021-09-02 14:49 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/RelativeFormQueryPlan.java
>  	public Optional<MultilineEntityResult> execute(QueryExecutionContext ctx, Entity entity) {
Das wäre schön aber denke nicht ganz so leicht umzusetzen, weil das hier ein Interace ist und auch an manchen stellen als interface benutzt wird.

2021-09-03 12:42 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/AbsoluteFormQueryPlan.java
> +	}
Habe es vorgezogen und jetzt gibt es eh kaum leere bodies mehr :)

2021-09-03 12:42 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/forms/managed/FormQueryPlan.java
> +		init(ctx, entity);
habe init vorgezogen

2021-09-03 12:45 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/messages/namespaces/specific/ExecuteQuery.java
> +			query.createQueryPlan(new QueryPlanContext(worker));
hab doku dazu gemacht?

2021-09-03 12:46 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/ArrayConceptQueryPlan.java
> +			initDateAggregator(validityDateAggregator, childPlans);
das aber was anderes oder?

2021-09-03 12:46 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	}
habs bei init belassen

2021-09-20 09:05 UTC, thoniTUB submitted a review, later dismissed

2021-09-20 09:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/EventIterating.java
> + * 3) {@link EventIterating#nextTable(QueryExecutionContext, Table)} (once per Table): Initializing the Event Iterating for the Table
Eigentlich nicht, aber eigentlich finde ich das ganz gut das als Parameter zu haben (sogar denkbar es ganz rauszuziehen), statt dass jede Klasse in der QueryEngine sich die Entity die ja eh immer gleich sit speichern muss.

2021-09-20 10:27 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/EventIterating.java
> + * 3) {@link EventIterating#nextTable(QueryExecutionContext, Table)} (once per Table): Initializing the Event Iterating for the Table
Zum mindest der ConceptQueryPlan speichert sich schonmal die Entity in der init ab

2021-09-20 12:17 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/EventIterating.java
> + * 3) {@link EventIterating#nextTable(QueryExecutionContext, Table)} (once per Table): Initializing the Event Iterating for the Table
Würde es erstmal so belassen für den FF und dann mit dir drüber reden wollen. Kann mir vorstellen, dass man die Entity in den Context steckt und überall den Context reinreicht. Bin mir aber nicht sicher ob das Gesund ist oder nicht.

2021-09-20 13:15 UTC, merged