Feature/admin api refresh token
bakdata/conquery pull request #2111
Opened 2021-10-01 15:50 UTC by thoniTUB

2021-10-04 13:47 UTC, awildturtok requested changes
Ich muss zugeben, dass ich nicht ganzz verstehe, was du in `JwtPkceVerifyingRealmFactory` machst, vielleicht wären in-line kommentare hilfreich, die sagen warum wir bestimmte Responses abschicken

2021-10-04 13:47 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +																				  .path(AdminServlet.ADMIN_UI)
warum für's admin UI?

2021-10-04 13:47 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +	private Response checkForRefreshToken(ContainerRequestContext request) {
du machst hier wie ich das sehe mehr als nur zu checken

2021-10-04 13:47 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +	@org.jetbrains.annotations.NotNull
falsche Anno?

2021-10-05 10:03 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +																				  .path(AdminServlet.ADMIN_UI)
Das der Auth Code Flow geproxied wird trifft nur für das AdminEnd zu, aber ich habe es jetzt generisch gemacht, so dass die RedirectUri aus dem Request erzeugt wird.

2021-10-05 10:04 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +	private Response checkForRefreshToken(ContainerRequestContext request) {
es ist jetzt ein checkAndRedeem

2021-10-05 10:05 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +	@org.jetbrains.annotations.NotNull
klascht mir Intellij manchmal rein, wenn es sich sicher ist dass es niemals null ist

2021-10-05 10:20 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +	@org.jetbrains.annotations.NotNull
Ist wieder raus

2021-10-05 14:03 UTC, awildturtok approved these changes
Danks für die Doku!

2021-10-06 10:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/auth/JwtPkceVerifyingRealmFactory.java
> +		if (wellKnownEndpoint == null) {
Ich habe es so gemacht, 
dass man es einfach haben kann und eine URL zum discovern konfigurieren kann
oder man liefert schon so die Daten die gebraucht werden per Config.

Für den erst Fall wollte ich aber das keine Start Dependency auf dem IDP besteht, also, dass der IDP beim Hochfahren nicht zwingend da sein muss.

2021-10-06 10:53 UTC, merged