allow configuration of ConqueryConfig from JSON-Test, simplifying tests
bakdata/conquery pull request #2293
Opened 2022-01-06 17:05 UTC by awildturtok

2022-01-10 09:09 UTC, Njimefo requested changes

2022-01-10 09:09 UTC, Njimefo commented on backend/src/test/java/com/bakdata/conquery/integration/IntegrationTests.java
> +		return newConf;
wenn die overrideConfig die Konfig zurückgigt, die übergeben wurde, warum gibst du das nicht direkt zurück?

2022-01-10 09:10 UTC, Njimefo reviewed
Ich habe nicht so richtig verstanden, was du geamcht hast, deswegen kamen auch wenig Kommentare. Das müssen wir noch besprechen.

2022-01-10 09:11 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/integration/IntegrationTests.java
> +		return newConf;
override config kann an der Stelle auch eine andere Config zurückliefern, zB aus den JSON-Tests, oder programmatisch überschrieben werden.

2022-01-11 09:33 UTC, thoniTUB requested changes
Nur ein Kleinigkeiten

2022-01-11 09:33 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/ConqueryConfig.java
>  	}
Das Festlegen auf `/api/` würde ich aus der Config raus lassen und in die `ApiV1.java` verlagern, da es hier sonst nichts zu konfigurieren gibt. Also so wie es im AdminServlet gemacht wird.

2022-01-11 09:33 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/IntegrationTest.java
>  	}
Für später oder zum Ausprobieren. Das ließe sich wahrscheinlich durch einen dynamischen Proxy elegant lösen

2022-01-11 09:33 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/json/AbstractQueryEngineTest.java
>  	}
warum ist das nicht in ConqueryTestSpec?

2022-01-11 09:33 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/json/FormTest.java
>  	}
Wenn die Funktion aus AbstractQueryEngineTest nach TestSpec wandert, dann können die Overrides weg denke ich

2022-01-11 09:33 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/integration/tests/ApiTokenRealmTest.java
>  import com.bakdata.conquery.apiv1.IdLabel;
Mich wundert, dass das immer noch passiert, obwohl wir mal die IDEs gesynct haben

2022-01-11 15:51 UTC, thoniTUB approved these changes

2022-01-11 15:52 UTC, merged