Feature/compound filter values
bakdata/conquery pull request #2378
Opened 2022-02-14 14:47 UTC by thoniTUB

2022-02-16 11:10 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/integration/json/filter/FilterTest.java
> +		if (expectedFrontendConfig != null) {
Die Idee ist cool, kannst du nur die assertion hinter das if packen? Das generieren+testen wäre immer wertvoll mMn

2022-02-16 11:10 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/datasets/concepts/filters/TestCompoundFilter.java
> +	@CompoundValueConfig(STRINGS)
Mit den Annos und dem Processor hast du dir ziemlich viel Magic eingekauft die du glaube ich gar nicht brauchst. Das könntest du denke ich über FieldNameConstants auf die CompoundValue-Klasse lösen, denn besonders viel nimmt dir der Processor wie ich es sehe gar nicht ab.

2022-02-16 11:10 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/datasets/concepts/filters/TestCompoundFilter.java
> +public class TestCompoundFilter extends SingleColumnFilter<TestCompoundFilter.CompoundFilterValue> {
Eine Sache die ich mich hier noch frage ist, wie du planst autocomplete oä für die Postleitzahlen drunter zu hudeln, der Ansatz an und für sich ist ja, dass wir das gelieferte Objekt beschreiben, und das finde ich gut.

2022-02-16 11:10 UTC, awildturtok commented on backend/src/test/resources/tests/filter/COMPOUND/content.csv
> +4,2015-03-18,ababab
Cooler Filter :D

2022-03-15 08:35 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/models/datasets/concepts/filters/TestCompoundFilter.java
> +	@CompoundValueConfig(STRINGS)
Ich habe es jetzt mit FieldNames umgesetzt, kannst du dir das mal bitte anschauen?

2022-03-29 08:56 UTC, awildturtok requested changes
Hauptsächlich Doku die mir fehlt aber ist im Grunde gut so

2022-03-29 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/frontend/FEFilterType.java
> +@NoArgsConstructor(access = AccessLevel.NONE)
Also hier erschließt sich mir leider immer noch nicht was du mit der Klasse erreichst.

2022-03-29 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/filter/FilterValue.java
> +	public static class GroupFilterValue extends FilterValue<Object> {
Doku bitte

2022-03-29 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/filter/FilterValue.java
> +		public GroupFilterValue deserialize(JsonParser p, DeserializationContext ctxt) throws IOException, JsonProcessingException {
Hier bitte ausführen warum du das so machst.

2022-03-29 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/filter/FilterValue.java
> +			final QueryContextResolvable value = ctxt.readValue(valueTraverse, ((GroupFilter) filter).getFilterValueType(ctxt.getTypeFactory()));
Kannst du das GroupFilter casten separat weiter oben machen? Dass es ein so wichtiger Teil ist, ist gar nicht so offensichtlich

2022-03-29 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/QueryContextResolvable.java
> +	}
Weil das ja ein relativ kleines interface ist würde ich die Methode nicht implementieren, sonst stolpert man schnell drüber wenn man es mal vergisst zu implementieren.

2022-03-29 08:56 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/datasets/concepts/filters/TestGroupFilter.java
> +public class TestGroupFilter extends SingleColumnFilter<TestGroupFilter.GroupFilterValue> implements GroupFilter {
Würde glaube ich in den Docs von GroupValue auf die Klasse als Beispiel verweisen

2022-03-29 10:28 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/frontend/FEFilterType.java
> +@NoArgsConstructor(access = AccessLevel.NONE)
Jetzt wo es kein Enum ist kann man es einfach erweitern und. Diese Werte werden ja für zweierlei Dinge gebraucht. Einmal für Serdes des FilterValues und um anderen um dem Frontend bescheid zugeben was gerendert werden soll.

Ersteres kann eigentlich weg, weil wir die Info auch aus der FilterId nehmen können.

2022-04-05 15:15 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/QueryContextResolvable.java
> +public interface QueryContextResolvable {
doku

2022-04-05 15:16 UTC, awildturtok commented
Sieht gut aus, müsste es aber in action sehen

2022-04-06 09:18 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/GroupedValue.java
> +public @interface GroupedValue {
Hab die Klasse gelöscht, wurde nicht mehr benutzt

2022-04-06 09:19 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CompoundValueConfig.java
> +public @interface CompoundValueConfig {
Die wurde auch nirgends mehr genutzt

2022-04-06 13:47 UTC, merged