Filter rows in table export query
bakdata/conquery pull request #2542
Opened 2022-06-09 13:02 UTC by awildturtok

2022-06-09 14:12 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +																  .filter(tbl -> tbl.getConnector().getColumn() != null)
Ja Konzepte die keinen Baum spannen haben keine Column

2022-06-09 14:59 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +					positions.putIfAbsent(validityDateColumn, 0);
> kann validityDateColumn doppelt zu position geadded werden?

Ja, bzw es gibt einige ValidityDateColumn. Die landen alle am Ende in der gleichen Spalte an Position 0.

2022-06-09 15:00 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +					positions.putIfAbsent(validityDateColumn, 0);
> wird die position nicht von jedem CQConcept überschrieben?

Nein, deren Ergebnisse werden ignoriert.

> oder kannst du dokumentieren wofür positions da ist?

Ja. Es ist ein Mapping der Spalten über alle Tables die wir exportieren in die Ausgabe-CSV Position.

2022-06-14 10:00 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +			}
ja, da war mal mehr drin. Kommt vlt wieder. Aber habs mal als Ternary umgesetzt.

2022-06-14 10:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +					   })
so wirklich einfach ist das gar nicht und einen echten mehrwert sehe ich hier gerade auch nicht, weil es später eh wieder ungrouped wird.

2022-06-14 10:20 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +					   })
oki :)

2022-06-15 12:49 UTC, thoniTUB requested changes
Sind nur kleine Umstrukturierungen

2022-06-15 12:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +	 */
💍

2022-06-15 12:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/filter/CQTable.java
> +	public Column findValidityDateColumn() {
Optional oder @Nullable wäre hier gut

2022-06-15 12:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		}
die beiden ifs müssen doch nicht für jedes Event abgefragt werden oder?

2022-06-15 12:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		query.acceptEvent(bucket, event);
das ist ein komischer seiteneffect von `isRowIncluded`

2022-06-15 12:51 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		query.acceptEvent(bucket, event);
die query wird pro Zeile ausgeführt :) Wird ja auch ganz am Anfang der Zeile initialisiert

2022-06-15 12:52 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		query.acceptEvent(bucket, event);
Vmtl fehlt hier die Doku, die erklärt, dass wir hier eine Query ausführen :D

2022-06-15 12:56 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		query.acceptEvent(bucket, event);
Aber kannst du diese Zeile dann nicht nach Ziele 91 verschieben?

2022-06-15 14:07 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		}
hab sie auf Bucket Ebene gezogen, ist ein bisschen ein waste noch, aber der Code ist dann etwas überschaubarer.

2022-06-15 14:08 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +		query.acceptEvent(bucket, event);
Habe die Doku ergänzt, dass klarer ist, was passiert.

2022-06-16 07:56 UTC, thoniTUB approved these changes

2022-06-16 07:57 UTC, merged