Concept Element Id output in concept column and Table Export
bakdata/conquery pull request #2567
Opened 2022-06-28 10:36 UTC by awildturtok

2022-07-04 13:41 UTC, thoniTUB requested changes

2022-07-04 14:04 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/ConceptColumnsAggregator.java
> +			final int[] mostSpecificChild = cblock.getEventMostSpecificChild(event);
```java
/**
	 * Method to get the element of this concept tree that has the specified local ID.
	 * This should only be used by the query engine itself as an index.
	 *
	 * @param ids the local id array to look for
	 * @return the element matching the most specific local id in the array
	 */
	public ConceptTreeNode<?> getElementByLocalId(@NonNull int[] ids) {
		int mostSpecific = ids[ids.length - 1];
		return localIdMap.get(mostSpecific);
	}
```

Ja es geht haha

2022-07-04 15:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +			  .map(cqUnfilteredTable -> cqUnfilteredTable.getConnector().getTable().getColumns())
hab sie gelöscht, war ungenutzt.

2022-07-04 15:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +		calculateColumnPositions(currentPosition, tables, secondaryIdPositions, positions);
jap ist besser, danke

2022-07-04 16:00 UTC, thoniTUB requested changes

2022-07-05 08:02 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = cblock.getMostSpecificChildLocalId(event);
Das ist die gleiche Logik ja, nur an anderen Stellen benutzt

2022-07-05 12:19 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +					: ResultType.resolveResultType(column.getType());
> Ist der ResultTyp nicht in jedem Fall auch der der Spalte? warum wird hier StringT genommen?

Im Falle einer ConceptColumn die nicht raw rauskommen soll, wird es zu string gemacht, dass man die Konzept-Ids ausgeben kann.

2022-07-05 12:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = List.of(bucket.getAsDateRange(event, column));
Weil es eine com.bakdata.conquery.ConqueryConstants#DATES_INFO Spalte ist, die ist List[DATER_RANGE]

2022-07-05 12:31 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/auth/IntrospectionDelegatingRealmTest.java
>  	}
ja das war der Fehlschalgende Test

2022-07-05 13:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +					: ResultType.resolveResultType(column.getType());
nein, das rawFormat kann beliebig sein, das ist ja der ursprüngliche Wert der Spalte (natürlich hat TreeConceptConnector die Validierung, dass die Spalte ein String ist, aber das würed ich trotzdem so offen halten)

2022-07-07 07:33 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/models/auth/IntrospectionDelegatingRealmTest.java
>  	}
Ist auf develop gefixed, also könntest du hier zurückrollen

2022-07-07 08:53 UTC, thoniTUB requested changes
Nur Kleinigkeiten

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/concept/ConceptColumnSelect.java
> + * When prettyPrint is true, the name of the Concept Element is used. Else, the ConceptElementId is returned.
```suggestion
 * When prettyPrint is true, the label of the Concept Element is used. Else, the ConceptElementId is returned.
```

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +	//TODO FK: Implement this as ValidityDateNode in QPNode instead.
Das das noch aktuell?

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +	 * Query used to filter for Entities. If subPlan is contained, tables will be exported for it.
```suggestion
	 * Query used to export tables filtered by entity. If the subPlan evaluates as contained for an entity, the corresponding table contents will be exported.
```

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = List.of(bucket.getAsDateRange(event, column));
Oki, ist die Spalte denn für einen Table-Export relevant? oder ist hier dann eine Doppelung der Daten drinne, weil es ja die einzeilspalten gibt und oft auch die virtuelle DateRange?

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +			entry[position] = bucket.createScriptValue(event, column);
Ja raw ist hier nicht das wie es im Speicher abgebildet ist sondern wie es in den Ausgangsdaten vorlag

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/ConceptColumnsAggregator.java
> +public class ConceptColumnsAggregator extends Aggregator<Set<Integer>> {
Doku pls

2022-07-07 08:53 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/ConceptColumnsAggregator.java
> +	}
Ist das nicht ListT[StringT]? Ansonsten UnsupportedOperationException

2022-07-07 08:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +	//TODO FK: Implement this as ValidityDateNode in QPNode instead.
Ja aber nicht für diesen PR

2022-07-07 08:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = List.of(bucket.getAsDateRange(event, column));
Alle ValidityDate Spalten werden nach vorne gezogen in eine Spalte, die ValidityDate-Spalte ergibt sich über die Anfrage. Das wird eben das EventDate. Dann gibt es noch andere DatumsSpalten, die auch mit-exportiert werden. Diese Spalte ist besonders, weil sie markiert, wann das Ereignis passiert ist, wie bei anderen Anfragen auch.

2022-07-07 09:00 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/ConceptColumnsAggregator.java
> +	}
Das Problem ist, dass das ein Mappender StringT ist, deswegen erzeugen wir ihn von Hand im Select, wo wir die entsprechenden infos haben.

2022-07-07 09:10 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/ConceptColumnsAggregator.java
> +	}
Ok, konnte es Problemlos zum Aggregator schieben.

2022-07-07 09:12 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
macht `com.bakdata.conquery.apiv1.QueryProcessor#postQuery` das nicht schon?

2022-07-07 10:22 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
Ach stimmt, dass vergesse ich immer, dass das eine das andere aufruft ;)

2022-07-07 12:07 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = List.of(bucket.getAsDateRange(event, column));
Oki, es sieht erstmal speziell geeignet für den SingleEntityExport aus. Wenn mal Subdatensätze exportiert werden sollen, dann sollte die spalte optional sein, aber das dann was für später

2022-07-07 12:12 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/TableExportQueryPlan.java
> +				entry[position] = cblock.getMostSpecificChildLocalId(event);
Wo wird jetzt wann was benutzt? Gehört der Select/Aggregartor zum SingleEntityExport?

2022-07-26 09:21 UTC, thoniTUB approved these changes

2022-07-26 09:21 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
>  	 * Multiple columns can map to the same output position:
@awildturtok ist develop hier schon reingemerged?

2022-07-26 09:21 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> +	public static String printValue(Concept concept, Object rawValue, PrintSettings printSettings) {
👍 
```suggestion
	/**
	 * rawValue is expected to be an Integer, expressing a localId for {@link TreeConcept#getElementByLocalId(int)}.
	 *
	 * If {@link PrintSettings#isPrettyPrint()} is true, {@link ConceptElement#getLabel()} is used to print.
	 * If {@link PrintSettings#isPrettyPrint()} is false, {@link ConceptElement#getId()} is used to print.
	 */
	public static String printValue(Concept concept, Object rawValue, PrintSettings printSettings) {
```

2022-07-26 09:21 UTC, thoniTUB commented on backend/src/test/java/com/bakdata/conquery/models/auth/IntrospectionDelegatingRealmTest.java
>  	}
Sollte so passen, wie es auf develop ist

2022-07-26 10:37 UTC, merged