adds missing suffix in output off StringTypePrefixSuffix
bakdata/conquery pull request #2587
Opened 2022-07-07 08:44 UTC by awildturtok

2022-07-14 11:34 UTC, awildturtok commented on backend/pom.xml
> +        </dependency>
Das war eine Warning in den Logs, die so weg ist.

2022-07-25 08:29 UTC, thoniTUB requested changes
Cool das da so viel Code weggefallen ist

2022-07-25 09:21 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/root/StringStore.java
> +		Set<Integer> actual = new HashSet<>();
=> rename to sampled

2022-07-25 09:34 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/root/StringStore.java
> +public interface StringStore extends ColumnStore {
TODO in die Stores reinschieben

2022-07-25 09:34 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/root/StringStore.java
> +public interface StringStore extends ColumnStore {
Und Namen der Stores von Type nach Store umschreiben

2022-07-25 14:46 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/dictionary/DictionaryMapping.java
> +			}
Also eigentlich wäre etwas komplett kaputt. Ich hatte es zum debuggen eingebaut, weil ich mich absichern wollte. Müsste vmtl eher eine Exception werfen.

2022-07-25 14:48 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/dictionary/MapDictionary.java
> +@ToString(callSuper = true)
> Kann das toString hier nicht ganzschön riesig werden?

Gut gesehen! Habe es angepasst wie ich es geplant hatte mit ToString.Include auf size, und onlyExplicitlyIncluded.

2022-07-25 14:48 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/root/StringStore.java
> +	@CPSType(id = "STRINGS_DESCRIPTION", base = ColumnStore.class)
ist wieder reingezogen. Bin mir nicht sicher ob es arg besser ist.

2022-07-25 14:50 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/jobs/ImportJob.java
> +				log.debug("Column[{}.{}.{}] part of shared Dictionary[{}]", table.getId(), importName, column.getName(), sharedDictionaryName);
Das Problem ist an der Stelle weiß man in den Logs nicht in welche Table man importiert, und die importName ist nicht unique. Sonst logged es einfach nur `20015-2022.spalte` was recht unnütz ist, wenn man viel logs hat.

2022-07-25 14:50 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/preproc/parser/specific/StringParser.java
> +		}
Kommentar war verrutscht.

2022-07-25 14:57 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/preproc/parser/specific/StringParser.java
> +				int intValue = Integer.parseInt(e.getKey());
> Wir sollten hier vielleicht gründlicher parsen, weil parseInt auch Tausendertrenner verschlucken kann, oder siehst du hier kein Problem?

uff, dann werde ich den check oben erweitern.

2022-07-25 15:18 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/preproc/parser/specific/StringParser.java
> +				int intValue = Integer.parseInt(e.getKey());
Musste selber nachschauen: der Conquery String ist Integer und das hier faked sich ja in einen Integer rein, deswegen :D

2022-07-26 08:51 UTC, thoniTUB approved these changes
Sieht gut aus, der leading-Zero-Check  im StringParser ist aber noch komisch

2022-07-26 08:51 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/preproc/parser/specific/StringParser.java
> +	private static final Pattern DIGITS = Pattern.compile("(^0$)|(^[1-9][0-9]*$)");
DIGITS_WITHOUT_ZERO_PADDING

2022-07-26 08:51 UTC, merged

2022-07-26 08:53 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/events/stores/specific/string/NumberStringStore.java
> +				return -1;
ne -1 hier schon richtig, man kann hier ja nicht garantieren, dass dem Store entsprechende Werte reinkommen. -1 ist so bisschen der contract, dass es ein nicht vorkommender Wert ist. Aber noch nie aktiv hinterfragt ob der Fall überhaupt vorkommen kann, dass Store-fremde Werte abgefragt werden können.

2022-07-26 09:04 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/preproc/parser/specific/StringParser.java
> +		 */
@awildturtok den hast du wohl übersehen