adds fixed Random-Seed
bakdata/conquery pull request #2632
Opened 2022-07-28 13:44 UTC by awildturtok

2022-08-02 07:49 UTC, thoniTUB reviewed
@awildturtok ich sehe noch nicht wie hier "konstante" Ergebnisse entstehen, weil der QueryExecutor beliebige entities auf einem Queryplan ausführt. Den Random kannst du im Init nicht zurücksetzen auf den Konstanten Seed zurücksetzen, du könntest vielleicht die entitiy-Id als Seed nehmen, dann wären die Ergebnisse zumindest für einen import lang konstant. Aber ich habe auch den Mythos gehört dass man nicht so viele Randoms alloziieren soll. Ist wahrscheinlich aufwändig, auch wenn es kein SecureRandom ist

2022-08-02 07:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/temporal/CQAbstractTemporalQuery.java
sampler.sampler: kann man das noch flacher machen?

2022-08-02 07:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/temporal/CQAbstractTemporalQuery.java
Oder getSampler umbenennen: SampleMode  oder so

2022-08-02 07:49 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/RandomValueAggregator.java
>  	private int event;
Klappt das überhaupt mit konstanten ergebnissen? Wir haben doch keine Kontrolle darüber welche entities vom QueryExecutor in diesen Aggregator gesteckt werden, oder? Das ist doch immer ein Race-Condition

2022-08-02 07:50 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/temporal/CQAbstractTemporalQuery.java
> Oder getSampler umbenennen: SampleMode oder so

ja Name muss ich ändern

2022-08-02 07:52 UTC, awildturtok commented
>  ich sehe noch nicht wie hier "konstante" Ergebnisse entstehen, weil der QueryExecutor beliebige entities auf einem Queryplan ausführt.

Jetzt wo du es sagst. Wir hatten schon gesehen, dass es pro Import nicht stabil ist, aber ausführung ist natürlich auch so nicht deterministisch :/ Ich muss mir nochmal Gedanken machen.

2022-08-04 13:26 UTC, thoniTUB requested changes
Es hat sich hier nicht viel geändert oder, man kann noch immer unterschiedliche Ergebnisse zwischen gleichen anfragen mit Random erhalten.

2022-08-04 13:26 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/temporal/TemporalSamplerFactory.java
> +				}
Hier bitte ein Kommentar ran, weshalb das so ist.

2022-08-04 13:26 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/value/RandomValueAggregator.java
>  	private int event;
hier hat sich nichts geändert, oder?

2022-08-04 13:38 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/temporal/TemporalSamplerFactory.java
> +
```suggestion
				// It would not produce sensible to just return random data.
```

2022-08-04 13:40 UTC, awildturtok commented
> man kann noch immer unterschiedliche Ergebnisse zwischen gleichen anfragen mit Random erhalten.

Es ging eigentlich auch nur um den TemporalSampler und den hatte ich gefixt. den RandomValuesAgg hatte ich übersehen, ist jetzt auch gefixt.

2022-08-12 08:55 UTC, thoniTUB approved these changes
Jetzt sieht es stabil aus

2022-08-12 08:55 UTC, merged