Multi column distinct summing
bakdata/conquery pull request #2671
Opened 2022-08-17 14:55 UTC by awildturtok

![grafik](https://user-images.githubusercontent.com/1553491/185172164-ecaa74b2-d944-45da-8484-9a75de45ca1d.png)

2022-08-17 15:48 UTC, thoniTUB requested changes

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
>  	private boolean distinct;
kann man das nicht weglassen?

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +	private List<Column> distinctByColumn;
```suggestion
	private List<Column> distinctByColumn = Collections.emptyList();
```

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
>  		}
```suggestion
		if (!distinctByColumn.isEmpty()) {
			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn()), DistinctValuesWrapperAggregator.fallback(distinctByColumn, getColumn())));
		}
```

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +		}
```suggestion
		out.addAll(distinctByColumn);
```

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/SumFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(getAggregator(), getDistinctByColumn()));
`isEmpty` finde ich besser, aber jetzt ist gerade kein default zu `Collections.emptyList()` da

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/connector/specific/CountSelect.java
> +	private List<Column> distinctByColumn;
distinct löschen und nur distinctByColumn mit default nutzen

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/connector/specific/SumSelect.java
> +	private List<Column> distinctByColumn = Collections.emptyList();
mui bene

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/connector/specific/SumSelect.java
> +	private List<Column> distinctByColumn = Collections.emptyList();
+ @NotNull

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/connector/specific/SumSelect.java
> +		if (distinctByColumn != null){
mit @NotNull sollte das immer true sein

2022-08-17 15:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	private final Set<List<Object>> observed = new HashSet<>();
Dann können wir uns bei Kollisionen nicht mehr sicher sein. Andererseits wir müssen sicher gehen, dass die objects nie `Object#hashCode` nutzen

2022-08-18 08:25 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
>  	private boolean distinct;
Das ist drin, weil es möglich ist auf die Spalte distinct zu machen, die gezählt wird, dann hat man keine Doppelung.

Aber bin mir gerade nicht sicher was ich besser finde:

```json
{
  "type" :"COUNT",
  "distinct" : true,
  "column" : "table.column1"
}


{
  "type" :"COUNT",
  "distinctByColumn" : ["table.column1"],
  "column" : "table.column1"
}


{
  "type" :"COUNT",
  "distinctByColumn" : ["table.other"],
  "column" : "table.column1"
}
```

Bei Count könnte man zumindest überlegen, ob man `distinctByColumn` dropped und `column` zu einem array macht, wobei dann size > 1 illegal ist wenn nicht auch distinct ist?

2022-08-18 10:29 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
>  	private boolean distinct;
ich bin mir nicht ganz sicher ob man `column` zu einem Array machen kann und `distinctByColumn` droppt,  weil der CountAggregator ein SingleColumn select ist

2022-08-18 10:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	private final Set<List<Object>> observed = new HashSet<>();
Also bei großem Set bleiben?

2022-08-18 10:58 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/DistinctValuesWrapperAggregator.java
> +	private final Set<List<Object>> observed = new HashSet<>();
ja sonst können wir uns nicht sicher sein

2022-08-18 11:07 UTC, thoniTUB reviewed
Bei den CountSelect/-Filter fände ich es doch besser wenn es explizit ist, welche column jetzt gezählt wird. Aus dem Json welches den Filter/Select definiert, wird man sonst nicht schlau wo und wie jetzt gezählt wird

2022-08-18 11:07 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn().get(0)), getColumn()));
Das ist jetzt ganz schon implizit. Ich würde `distinct` streichen und `distinctByColumn` beibehalten

2022-08-18 11:07 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/connector/specific/CountSelect.java
> +			return new DistinctValuesWrapperAggregator<>(new CountAggregator(getColumn().get(0)), getColumn());
Wie beim CountFilter. Das es implizit die erste angegebene column ist ist schwierig

2022-08-18 14:59 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn().get(0)), getColumn()));
Da ist nichts implizit, der CountFilter wird eh nicht aufgerufen wenn nicht alle spalten gesetzt sind

2022-08-22 14:25 UTC, thoniTUB submitted a review, later dismissed

2022-08-22 14:25 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn().get(0)), getColumn()));
Ah okay, aber soll es so sein, dann "löchrige" zeilen dann ignoriert werden? Ich bin mir nicht sicher, ob dass für alle anwendungsfälle passt

2022-08-23 10:16 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn().get(0)), getColumn()));
> Ah okay, aber soll es so sein, dann "löchrige" zeilen dann ignoriert werden? Ich bin mir nicht sicher, ob dass für alle anwendungsfälle passt

Ich merge es mal so, merke es aber im Ticket an

2022-08-25 14:12 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/CountFilter.java
> +			return new RangeFilterNode(value, new DistinctValuesWrapperAggregator(new CountAggregator(getColumn().get(0)), getColumn()));
Ok, das war gut, dass du das angemerkt hast, die löchrigen zeilen sind relevant

2022-08-25 14:15 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/filters/specific/SumFilter.java
>  		}
guter Punkt, ist mir gar nicht aufgefallen.

2022-08-25 14:55 UTC, thoniTUB approved these changes

2022-08-25 14:58 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/queryplan/aggregators/specific/CountAggregator.java
>  	}
Genau, wenn column gesetzt ist zählt er vorhandene events, wenn column null ist, zählt es alles, das ist vor allem relevant in kombination mit dem DistinctWrapper, wo dann column null ist

2022-08-25 15:30 UTC, merged