Flatten /api removing redundant ids
bakdata/conquery pull request #2812
Opened 2022-11-21 13:40 UTC by awildturtok

2022-11-22 09:32 UTC, thoniTUB requested changes

2022-11-22 09:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/FilterResource.java
>  			throw new BadRequestException(e);
Der Endpunkt prüft gerade keine Permissions

2022-11-22 09:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/DatasetQueryResource.java
> +	}
Bitte in eine extra Klasse in api-Package packen

2022-11-22 09:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/ConceptResource.java
> +		subject.authorize(concept, Ability.READ);
dataset:READ wird nicht getestet

2022-11-22 09:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/ConceptResource.java
>  		return Response.ok(result).tag(result.getCacheId()).build();
Hier gibts auch keine Permissions mehr

2022-11-22 09:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/result/arrow/ResultArrowProcessor.java
> +				exec.getDataset(), // TODO pull dataset up
Kann jetzt eigentlich auch runtergepusht werden, wenn es aus der exec kommt

2022-11-22 13:20 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/FilterResource.java
>  			throw new BadRequestException(e);
> Der Endpunkt prüft gerade keine Permissions

Bin mal über alle rüber gegangen

2022-12-02 11:45 UTC, thoniTUB requested changes

2022-12-02 11:45 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/DatasetFormConfigResource.java
> +public class DatasetFormConfigResource extends HAuthorized {
Kannst du hier bitte auch noch das Dataset prüfen?

2022-12-02 11:45 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +	public <E extends ManagedExecution<?> & SingleTableResult> Response getAsCsv(@Auth Subject subject, @PathParam(QUERY) ManagedExecution<?> execution, @HeaderParam(HttpHeaders.USER_AGENT) String userA
Vorher war es lesbarer

2022-12-02 11:45 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/hierarchies/HAuthorized.java
> +	@Context
Wir die Klasse noch benutzt?

2022-12-05 10:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/hierarchies/HAuthorized.java
> +	@Context
> Wir die Klasse noch benutzt?

ist weg

2022-12-05 10:37 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultCsvResource.java
> +	public <E extends ManagedExecution<?> & SingleTableResult> Response getAsCsv(@Auth Subject subject, @PathParam(QUERY) ManagedExecution<?> execution, @HeaderParam(HttpHeaders.USER_AGENT) String userA
komisch, Intellij will hier nicht choppen. Habs händisch gemacht

2022-12-13 10:41 UTC, thoniTUB approved these changes

2022-12-13 10:42 UTC, merged